### ISSUE TITLE
href link in the Hyperlink "Jython.jar" in SETUP section

### ISSUE THREAD

**Issue by bhardwajaadesh0001** [vsec7/BurpSuite-Xkeys#1]
The reference link should be:
https://www.jython.org/download.html
Instead of
https://www.jython.org/downloads.html

**Comment by vsec7** [comment]
Thanks , sorry for my misstyped :)

**Comment by bhardwajaadesh0001** [comment]
Still not updated.
I have forked and changed the "href" link.

Hope you understand :)

**Comment by vsec7** [comment]
Uh, I changed in requirements section only, 
And now all link has updated ,
thanks again :)

**Comment by ghost** [comment]
Yeah, it's done ;)
Great Work!
